# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./httproute.yaml

helmCharts:
- name: redisinsight
  repo: https://heywood8.github.io/helm-charts
  releaseName: redis-insight
  namespace: infrastructure
  version: 0.4.5
  valuesFile: values.yaml
