apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: gateway
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: v0.15.3
    helm:
      releaseName: metallb
      values: |
        configInline:
          address-pools:
            - name: default-pool
              protocol: layer2
              addresses:
                - 192.168.1.155-192.168.1.160
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
