apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- releaseName: nfs-subdir-external-provider
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  name: nfs-subdir-external-provisioner
  namespace: infrastructure
  valuesFile: ./values.yaml
  version: 4.0.18
