apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- ./route.yaml

helmCharts:
- name: kube-prometheus-stack
  releaseName: prometheus
  repo: oci://ghcr.io/prometheus-community/charts/
  namespace: monitoring
  valuesFile: ./values.yaml
  version: 81.5.0
