apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-server
  namespace: gateway-apis
spec:
  parentRefs:
  - name: traefik
    namespace: gateway-apis
  hostnames:
  - argocd.int.midugh.fr
  rules:
  - matches:
    - path:
        value: /
        type: PathPrefix
    backendRefs:
    - name: argocd-server
      port: 80
