apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- releaseName: gateway-internal
  repo: oci://ghcr.io/nginx/charts/
  name: nginx-gateway-fabric
  namespace: gateway-apis
  version: 2.4.1
  valuesFile: values-internal.yaml
