apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - "https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v2.4.1/deploy/crds.yaml"
# - "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.4.0"
- ./gateway-internal.yaml

helmCharts:
- releaseName: nginx-gateway-fabric
  repo: oci://ghcr.io/nginx/charts/
  name: nginx-gateway-fabric
  namespace: gateway-apis
  version: 2.4.1
