apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/traefik/traefik/v3.6/docs/content/reference/dynamic-configuration/kubernetes-gateway-rbac.yml
- ./gateway-internal.yaml

helmCharts:
- releaseName: traefik
  repo: oci://ghcr.io/traefik/helm/
  name: traefik
  namespace: gateway-apis
  valuesFile: ./values.yaml
  version: 39.0.0
